### ISSUE TITLE
Pull access denied for ldap-overleaf-sl

### ISSUE THREAD

**Issue by c0r3dump3d** [smhaller/ldap-overleaf-sl#1]
Hi, very interesting project ... but it doesn't work, when I try to start the docker-composer I have this error:

`ERROR: pull access denied for ldap-overleaf-sl, repository does not exist or may require 'docker login'

**Comment by andreas-bulling** [comment]
Solution: ensure to run `make`, then modify the following line in `docker-compose.yml`
`image: ldap-overleaf-sl:latest`

**Comment by smhaller** [comment]
thx - I changed the line in docker-compose.
