### ISSUE TITLE
How to access windows active directory?

### ISSUE THREAD

**Issue by looong-cat** [smhaller/ldap-overleaf-sl#14]
I'm use "sAMAccountName" as uid，but it didn't work。
You are also using windows active directory?
thank you in advance.

**Comment by smhaller** [comment]
I do not have any windows machine/server. I am using openldap. Can you enable the logging and tell me what requests you send to the AD server and what the response is?

**Comment by smhaller** [comment]
Closing this one. If there is more info then we can re-open it.
