### ISSUE TITLE
version without certbot / traefik

### ISSUE THREAD

**Issue by hoelscher-berlin** [smhaller/ldap-overleaf-sl#18]
Hey, first of all, I appreciate your efforts to build a LDAP solution for sharelatex. I was happy to see this improved version makes it possible to set a different base DN, in worksasintended's version this part is hard coded.

I would like to use this with my own reverse proxy running. So only port 80 and no traefik / certbot. Is this possible without any major changes, and if yes, could you point me towards the right changes in the docker-compose.yml?

Thanks, Simon

**Comment by smhaller** [comment]
This should be easily done: you can just take the docker-compose.certbot.yml
- comment or remove the certbot part (lines 132-148)
- change the port of the Overleaf instance to 80 (line 16). 
- comment or remove the link to the simple-certbot (line 20)

This should be it. If you encounter any issues just write me or open a issue.
