### ISSUE TITLE
error: Tracker "idealTree" already exists

### ISSUE THREAD

**Issue by andreas-bulling** [smhaller/ldap-overleaf-sl#2]
Hi,

I tried to follow your instructions but I receive the following error
```
[...]
Step 7/31 : RUN npm install ldapts-search
 ---> Running in 5ceb10366306
npm ERR! Tracker "idealTree" already exists

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-20T17_09_37_696Z-debug.log
The command '/bin/sh -c npm install ldapts-search' returned a non-zero code: 1
```

**Comment by smhaller** [comment]
hm, there seem to be changes in nodejs 15 
  - see https://stackoverflow.com/questions/57534295/

i added two lines:
workdir /opt

and a clean cache 

please can you try again (i might be able to test this at the end of this week)

**Comment by andreas-bulling** [comment]
I had added a /var/www/sharelatex workdir - that worked so I assume your fix also does

**Comment by smhaller** [comment]
Thx, I don't think it really matters but I changed the workdir also to /var/www/sharelatex
