### ISSUE TITLE
LDAPS with self-signed cert

### ISSUE THREAD

**Issue by tinkerdudeno1** [smhaller/ldap-overleaf-sl#20]
I need to migrate my ldap connection to ldaps. Unfortunately the Active Directory's certificate is signed by our internal CA so it's generally not trusted by any libraries. I tried to install the cert in the system cert store but it seams the according library uses it's on trust store and ignores the system's. I've been looking at the code of this repo for almost an hour now but have not come very far. I understand that there is a `Client` object which comes from the `ldapts` library which probably does all the TLS-dance and verfies the certificate and everything. And then I got stuck...
Is there a possibility to manually pass in a trusted ca-cert when connecting? If so, it would be awesome if one could pass a cert in as an environment variable...
Or is there an even simpler solution? I'm glad to see the default config also uses TLS so it's really just a detail which is in my way...
Thanks in advance!

**Comment by smhaller** [comment]
I think all you have to do is:

1. get the server certificate pem file.
2. put the file as e.g. server-cert.pem in the folder  with the Dockerfile (ldap-overleaf-sl)
3. add the following line in the Dockerfile: 
``COPY server-cert.pem /etc/ssl/certs/server-cert.pem``
4. adapt the sharelatex/AuthenticationManager.js:
  - Add the filesystem requirement (@ e.g. line 14): 
  ``const fs = require('fs');`` 
  - Add tls options in the Object creation of the ldapts client (@ line 271): 
    ``` 
    url: process.env.LDAP_SERVER,
    tlsOptions: {
        ca: [ fs.readFileSync('/etc/ssl/certs/server-cert.pem') ],
    }, 
    ``` 
5. Recreate the docker image with ``make`` and restart the container.

Please let me know if this did work. If this works i'll think about a solution to pass this via an environment variable.

**Comment by nehart** [comment]
Hi @smhaller,
I ran into the same issue...
...I just want to inform you that these changes in AuthenticationManager.js are working!

BR,
Norbert.

**Comment by qk4l** [comment]
Nowdays it is just enough to set env variable  LDAP_SERVER_CACERT with a path to CA which could easily mount during docker run

**Comment by yzx9** [comment]
Closed since the `LDAP_SERVER_CACERT` has been added. Special thanks to the tests conducted by @nehart and @qk4l!
