### ISSUE TITLE
Session error

### ISSUE THREAD

**Issue by yuguoshao** [smhaller/ldap-overleaf-sl#21]
I've tried many many times. But always get the following, when I want to login.
`Session error. Please check you have cookies enabled. If the problem persists, try clearing your cache and cookies.`

**Comment by yuguoshao** [comment]
The Chrome log told me 404 error.

**Comment by smhaller** [comment]
Did you configure the .env environment? Are you unsing traefik or certbot? If you are on your server instance can you connect directly from your terminal (e.g. via w3m)? Can you post the output of ```docker logs  ldap-overleaf``` instance? And the logs from the sharelatex within the sharelatex docker container e.g. web.log...

For the little information above i think the docker container running the sharelatex instance is not running.

**Comment by yuguoshao** [comment]
Thank you very much for reply. Yes I've configure the .env file. And I try traefik and certbot (session error appeared in all ),now I am testing on certbot. For terminal connect, I use w3m in containers "ldap-overleaf-sl" visit `127.0.0.1` after click login it return "Forbidden".

docker logs ldap-overleaf-sl:

`
*** Running /etc/my_init.d/00_make_sharelatex_data_dirs.sh...

*** Running /etc/my_init.d/00_regen_sharelatex_secrets.sh...

*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...

*** Running /etc/my_init.d/00_set_docker_host_ipaddress.sh...

*** Running /etc/my_init.d/01_nginx_config_template.sh...

*** Running /etc/my_init.d/10_delete_old_logs.sh...

*** Running /etc/my_init.d/10_syslog-ng.init...

*** Running /etc/my_init.d/98_check_db_access.sh...

Mongodb is up.

Redis is up.

*** Running /etc/my_init.d/99_run_web_migrations.sh...

generating random secrets

Nginx: generating config file from template

Nginx: reloading config

 * Reloading nginx configuration nginx

   ...done.

Mar  8 02:46:13 c71b32c4153a syslog-ng[73]: syslog-ng starting up; version='3.13.2'

Checking can connect to mongo and redis

Using default settings from /var/www/sharelatex/web/config/settings.defaults.js

Using settings from /etc/sharelatex/settings.js

Using default settings from /var/www/sharelatex/web/config/settings.defaults.js

Using settings from /etc/sharelatex/settings.js

All checks passed

Running migrations for server-ce


> web-overleaf@0.1.4 migrations

> east "migrate" "-t" "server-ce"


Using default settings from /var/www/sharelatex/web/config/settings.defaults.js

Using settings from /etc/sharelatex/settings.js

Nothing to migrate

Finished migrations

Mar  8 02:46:18 c71b32c4153a cron[143]: (CRON) INFO (pidfile fd = 3)

Mar  8 02:46:18 c71b32c4153a cron[143]: (CRON) INFO (Running @reboot jobs)

*** Booting runit daemon...

*** Runit started as PID 129
`

web.log:

`{"name":"web","hostname":"c71b32c4153a","pid":156,"level":30,"req":{"url":"/login","method":"GET","remote-addr":"172.22.0.1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36"},"res":{"statusCode":200},"response-time":199,"msg":"GET /login","time":"2022-03-08T02:59:35.113Z","v":0}
{"name":"web","hostname":"c71b32c4153a","pid":156,"level":40,"err":{"message":"invalid csrf token","name":"ForbiddenError","stack":"ForbiddenError: invalid csrf token\n    at csrf (/var/www/sharelatex/web/node_modules/csurf/index.js:112:19)\n    at Csrf.middleware (/var/www/sharelatex/web/app/src/infrastructure/Csrf.js:65:14)\n    at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:317:13)\n    at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:335:12)\n    at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:275:10)\n    at SessionStrategy.strategy.pass (/var/www/sharelatex/web/node_modules/passport/lib/middleware/authenticate.js:343:9)\n    at SessionStrategy.authenticate (/var/www/sharelatex/web/node_modules/passport/lib/strategies/session.js:75:10)\n    at attempt (/var/www/sharelatex/web/node_modules/passport/lib/middleware/authenticate.js:366:16)\n    at authenticate (/var/www/sharelatex/web/node_modules/passport/lib/middleware/authenticate.js:367:7)\n    at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:317:13)\n    at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:335:12)\n    at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:275:10)\n    at initialize (/var/www/sharelatex/web/node_modules/passport/lib/middleware/initialize.js:53:5)\n    at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:317:13)\n    at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:335:12)\n    at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:275:10)","info":{},"code":"EBADCSRFTOKEN"},"url":"/login","method":"POST","user":null,"msg":"invalid csrf","time":"2022-03-08T02:59:39.150Z","v":0}
{"name":"web","hostname":"c71b32c4153a","pid":156,"level":30,"req":{"url":"/login","method":"POST","referrer":"http://127.0.0.1:88/login","remote-addr":"172.22.0.1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36","content-length":"81"},"res":{"statusCode":403},"response-time":6,"msg":"POST /login","time":"2022-03-08T02:59:39.151Z","v":0}`

Thank you very much!

**Comment by smhaller** [comment]
Ok. Now could you access the external url/ip from your server where you host the containers and show me the logs from web.log during login? 

Should be something like:

```
[{"dn":"uid=simon.haller,ou=people,dc=informatik,dc=uibk,dc=ac,dc=at","objectClass":["inetOrgPerson","organizationalPerson","posixAccount","shadowAccount","person"],"uid":"simon.haller","preferredLanguage":"en_US","shadowMax":"99999","shadowWarning":"7","uidNumber":"53679","homeDirectory":"/home/simon.haller","loginShell":"/bin/bash","gidNumber":"1101","shadowLastChange":"17843","userPassword":"XXXXXXXX","mail":"XXXXXXXXX","givenName":"Simon","cn":"Simon Haller-Seeber","sn":"Haller-Seeber","gecos":"Simon Haller-Seeber"}]
Found user: XXXXXX Name: Simon Haller-Seeber DN: uid=simon.haller,ou=people,dc=informatik,dc=uibk,dc=ac,dc=at
is Admin
{"name":"web","hostname":"953e7720eed0","pid":163,"level":30,"msg":"[Metrics] expected wrapped method 'updateUser' to be invoked with a callback","time":"2022-03-08T13:21:02.334Z","v":0}
{"name":"web","hostname":"953e7720eed0","pid":163,"level":30,"email":"simon.haller@uibk.ac.at","user_id":"5eba5e00088aeb0086a124ec","msg":"successful log in","time":"2022-03-08T13:21:02.335Z","v":0}
{"name":"web","hostname":"953e7720eed0","pid":163,"level":30,"key":"mongo.UserUpdater.updateUser","args":{"0":"5eba5e00088aeb0086a124ec"},"elapsedTime":11,"msg":"[Metrics] timed async method call","time":"2022-03-08T13:21:02.344Z","v":0}
{"name":"web","hostname":"953e7720eed0","pid":163,"level":30,"req":{"url":"/login","method":"POST","referrer":"https://ifi-exp.uibk.ac.at/login","remote-addr":"138.232.53.96","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0","content-length":"97"},"res":{"statusCode":200},"response-time":118,"msg":"POST /login","time":"2022-03-08T13:21:02.354Z","v":0}
{"name":"web","hostname":"953e7720eed0","pid":163,"level":30,"user_id":"5eba5e00088aeb0086a124ec","msg":"got users subscription","time":"2022-03-08T13:21:02.564Z","v":0}
{"name":"web","hostname":"953e7720eed0","pid":163,"level":30,"key":"mongo.UserGetter.getUser","args":{"0":"5eba5e00088aeb0086a124ec"},"elapsedTime":65,"msg":"[Metrics] timed async method call","time":"2022-03-08T13:21:02.569Z","v":0}
```

**Comment by yuguoshao** [comment]
Sorry i've made mistake. While Session error happened , chrome logged 403 error.
And the web.log during login is 
`{"name":"web","hostname":"c71b32c4153a","pid":156,"level":40,"err":{"message":"invalid csrf token","name":"ForbiddenError","stack":"ForbiddenError: invalid csrf token\n    at csrf (/var/www/sharelatex/web/node_modules/csurf/index.js:112:19)\n    at Csrf.middleware (/var/www/sharelatex/web/app/src/infrastructure/Csrf.js:65:14)\n    at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:317:13)\n    at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:335:12)\n    at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:275:10)\n    at SessionStrategy.strategy.pass (/var/www/sharelatex/web/node_modules/passport/lib/middleware/authenticate.js:343:9)\n    at SessionStrategy.authenticate (/var/www/sharelatex/web/node_modules/passport/lib/strategies/session.js:75:10)\n    at attempt (/var/www/sharelatex/web/node_modules/passport/lib/middleware/authenticate.js:366:16)\n    at authenticate (/var/www/sharelatex/web/node_modules/passport/lib/middleware/authenticate.js:367:7)\n    at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:317:13)\n    at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:335:12)\n    at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:275:10)\n    at initialize (/var/www/sharelatex/web/node_modules/passport/lib/middleware/initialize.js:53:5)\n    at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:317:13)\n    at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:335:12)\n    at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:275:10)","info":{},"code":"EBADCSRFTOKEN"},"url":"/login","method":"POST","user":null,"msg":"invalid csrf","time":"2022-03-08T13:37:21.993Z","v":0}
{"name":"web","hostname":"c71b32c4153a","pid":156,"level":30,"req":{"url":"/login","method":"POST","referrer":"http://192.168.1.204:88/login","remote-addr":"172.22.0.1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36","content-length":"81"},"res":{"statusCode":403},"response-time":2,"msg":"POST /login","time":"2022-03-08T13:37:21.994Z","v":0}
{"name":"web","hostname":"c71b32c4153a","pid":156,"level":30,"rss":"136.01","heapTotal":"85.85","heapUsed":"72.89","external":"20.04","arrayBuffers":"18.45","msg":"process.memoryUsage()","time":"2022-03-08T13:37:23.140Z","v":0}`

**Comment by smhaller** [comment]
can you try via https - it looks like that you try to access the webpage via http... - Am i correct?

**Comment by yuguoshao** [comment]
Yeah it is via http. I exposed 80 and 443 of containers '[ldap-overleaf-sl]'.
For http 80 I met session error.
For http 443 There is no response.
Is there any relations with certbot ? I want to access overleaf via ip ,So I filled a fake domain in .env.

**Comment by smhaller** [comment]
Yes this might be the reason. In this setup everything is configured to use certificates and correct domains. 
What you might try is to configure your hostname or your IP as domain (in ``.env``). 

Then create a self signed certificate: e.g. 
``openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365 -nodes -subj "/CN=$HOSTNAME"``

You might use your IP-address instead of  $HOSTNAME - but use the same as in the ``.env`` configuration.
To check your self signed certificate: ``openssl x509 -in cert.pem -text``

Then configure line 24 in  docker-compose.certbot.yml that the sharelatex container can use your self signed certificate.
Additionally configure nginx/sharelatex.conf. port 80 should redircet. port 443 should use your self signed certificate.

Then recreate the sharelatex container with ``make`` and restart them.

I think that this should work.

**Comment by yuguoshao** [comment]
Sorry I think in [https://github.com/smhaller/ldap-overleaf-sl/blob/master/ldap-overleaf-sl/nginx/sharelatex.conf](url) the nginx conf file , nginx won't listen 443 port (be annotated).

**Comment by smhaller** [comment]
Yes, like i wrote uncomment the comments in sharelatex.conf and configure it to use your self signed certificate (which you share via the docker-cpmpose file). As an example you can also have a look at the comment from Christf in issue #17.

**Comment by yuguoshao** [comment]
Well I take a long time to fix the problem, Thank you very much for your help !!!
And the problem can be fixed by remove `SHARELATEX_SECURE_COOKIE: 'true'` (Althrough it's not safe).
When I fixed it I faced a new error, The following is sharelatex/web.log
> Found user: undefined Name: undefined root DN: cn=root,ou=Users,dc=bimsa,dc=cn
>is Admin
>events.js:291
>      throw er; // Unhandled 'error' event
>      ^
>
>TypeError: Cannot read property 'trim' of null
>    at Object.getUserByAnyEmail (/var/www/sharelatex/web/app/src/Features/User/UserGetter.js:132:19)
>    at Object.obj.<computed> [as getUserByAnyEmail] (/var/www/sharelatex/web/node_modules/@overleaf/metrics/timeAsyncMethod.js:50:43)
>    at Object.registerNewUser (/var/www/sharelatex/web/app/src/Features/User/UserRegistrationHandler.js:50:16)
>    at createIfNotExistAndLogin (/var/www/sharelatex/web/app/src/Features/Authentication/AuthenticationManager.js:63:19)
>    at /var/www/sharelatex/web/app/src/Features/Authentication/AuthenticationManager.js:377:9
>    at /var/www/sharelatex/web/node_modules/mongoose/lib/model.js:4842:16
>    at /var/www/sharelatex/web/node_modules/mongoose/lib/model.js:4842:16
>    at /var/www/sharelatex/web/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
>    at /var/www/sharelatex/web/node_modules/mongoose/lib/model.js:4865:21
>    at /var/www/sharelatex/web/node_modules/mongoose/lib/query.js:4419:11
>    at /var/www/sharelatex/web/node_modules/kareem/index.js:135:16
>    at processTicksAndRejections (internal/process/task_queues.js:79:11)
>    at runNextTicks (internal/process/task_queues.js:66:3)
>    at processImmediate (internal/timers.js:434:9)
>Emitted 'error' event on Function instance at:
>
>Set UV_THREADPOOL_SIZE=16
>ENABLE_TRACE_AGENT set to undefined
>ENABLE_DEBUG_AGENT set to undefined
>ENABLE_PROFILE_AGENT set to undefined
>Using default settings from /var/www/sharelatex/web/config/settings.defaults.js
>Using settings from /etc/sharelatex/settings.js

**Comment by yuguoshao** [comment]
Oh that’s because there is no email field in ldap user.

**Comment by smhaller** [comment]
Does it work now? Or can I help somehow?

**Comment by yuguoshao** [comment]
It works !!! Thank you!!
