### ISSUE TITLE
Update to Sharelatex 3.5

### ISSUE THREAD

**Issue by colfes** [smhaller/ldap-overleaf-sl#25]
This is probably on your ToDo-List already, but an update to support Sharelatex 3.5 would be great! :)

**Comment by smhaller** [comment]
The Authentication structure changed a bit from v3.3.2 to 3.5: I'll have time to have a proper look at it during the Easter holidays - if you need it earlier you can have a look at the `AuthenticationManager.js`:
compare the original `/overleaf/services/web/app/src/Features/Authentication/AuthenticationManager.js` vs the one in this repo.
in `ContactController.js` you most probably just need to remove line 16.

**Comment by VPaulV** [comment]
Thank you. I am not very good with js. Could you point me into the direction of what changes do I need to port AuthenticationManager?

Looks like I just need to add ldapAuth and change createIfNotExistAndLogin, createIfNotExistAndLogin, createIfNotExistAndLogin functions. Is it correct or I am missing something?

**Comment by yzx9** [comment]
closed as stale since we has support 4.1.1
