### ISSUE TITLE
Admin Panel doesn't work

### ISSUE THREAD

**Issue by nehart** [smhaller/ldap-overleaf-sl#27]
Hi,
First, thanks for the perfect adoption on overleaf.

Besides the admin panel, everything is working ...
... I have no content, when I open the panel... It doesn't matter if I do this with an local or LDAP admin.

Have I done something wrong, or is this a bug?
What would you need from me in order to be able to support?

I am using the latest version on this GitHub repository.

![admin_panel](https://github.com/smhaller/ldap-overleaf-sl/assets/22591383/884ea09a-f652-4dba-8bf5-a00bfbe7479e)

**Comment by smhaller** [comment]
can you try to comment line 61 in ldap-overleaf-sl/Dockerfile
and re-build the Image

**Comment by nehart** [comment]
Hi,
Yes... sure.... THANKS!!!!!!... should be possible on the weekend... I will keep you posted!

BR,
Norbert.

**Comment by nehart** [comment]
Unfortunately, it didn't work to remove the following line ....

```code
#rm /overleaf/services/web/modules/user-activate/app/views/user/register.pug && \
```

You have updated the Dockerfile, right?
I had to comment out the line with "share.pug" due to an error that the file is missing!

```code
## share.pug file was removed in later versions
#sed -iE "s%placeholder=.*$%placeholder=\"${collab_text}\"%g" /overleaf/services/web/app/views/project/editor/share.pug && \
```

BR,
Norbert.

**Comment by nehart** [comment]
Maybe this error message from Firefox helps

```code
Error: [$controller:ctrlreg] The controller with the name 'RegisterUsersController' is not registered.
https://errors.angularjs.org/1.8.2/$controller/ctrlreg?p0=RegisterUsersController
    i https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    get https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    g https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    ae https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    ue https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    ue https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    ue https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    ue https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    ue https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    ue https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    oe https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    i https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    $eval https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    $apply https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    i https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    invoke https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    i https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    Ce https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    <anonymous> https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    <anonymous> https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    <anonymous> https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    <anonymous> https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
    <anonymous> https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
 
Object { tags: {…}, extra: {} }
​
extra: Object {  }
​
tags: Object { handler: "angular-exception-handler" }
​
<prototype>: Object { … }
main-1ca8047f80eb1ecaf033.js:2:933988
    <anonymous> https://test03.int.ehart.net/js/main-1ca8047f80eb1ecaf033.js:2
```

**Comment by holema** [comment]
Hello,
i face the same issue.

**Comment by holema** [comment]
I found a way to fix this isue:
in the new version of this file there is no card with a controller, so I removed this from the card and now the admin page is working.
I don't know if there is something missing but as a workaround this is a possibility.

```
 .col-xs-12
                                        .card
                                                .page-header

```
![image](https://github.com/smhaller/ldap-overleaf-sl/assets/22790152/9e65f8a1-e511-45c2-9093-22d7dea4b455)

**Comment by VPaulV** [comment]
@holema thx! Works for me as well

**Comment by smhaller** [comment]
Please reopen if the patch does not work for you

**Comment by tinkerdudeno1** [comment]
~~Sorry to have to dig this up again: Where do I erase the lines mentioned above to make the admin panel work again, I cannot seem to find the correct place...~~
I just found out I am not working on the latest version, but on the latest release. I'll try upgrading but I just saw that you committed a change which will fix this.
Nevermind!
