### ISSUE TITLE
Implement Marker-Based Patching Mechanism for File Modification

### ISSUE THREAD

**Issue by yzx9** [smhaller/ldap-overleaf-sl#34]
Current file modification strategies primarily include two approaches:

- **Complete File Replacement**: This method have to involves importing the entire original file. For instance, in #33, adding just six lines of code required importing over 2000 lines from the `router.js` file. The drawbacks are significant; it not only necessitates the import of the entire file but also requires manual updates whenever the upstream file changes.
- **`sed` Command for Single-Line Edits**: While useful for single-line modifications, this approach falls short when dealing with multi-line changes.

This issue introduces a marker-based replacement method, essentially an enhanced version of the `sed` command. Its key advantages are:

- **No Need to Import the Entire Original File**: This method eliminates the need to import large files for minor edits.
- **Easier Synchronization with Upstream Changes**: It simplifies updating in response to changes in the original file.
- **Multi-Line Applicability**: Unlike sed, it is well-suited for modifications spanning multiple lines.
- **Clearer Patch Files**: The patch files are more concise and understandable.

If you are interested in this solution, I am ready to submit a PR for its implementation..

**Comment by VPaulV** [comment]
I am curious, why do you need to write a script for patching, instead of just using i.e. [patch](https://man7.org/linux/man-pages/man1/patch.1.html) ?

**Comment by yzx9** [comment]
> I am curious, why do you need to write a script for patching, instead of just using i.e. [patch](https://man7.org/linux/man-pages/man1/patch.1.html) ?

Ahahaha, you're absolutely right! I was so engrossed in looking for a substitute for `sed` that I forgot this is a common case. The `patch` command is a great solution. Ironically, my code ended up being a poorer version of the `patch` command.

**Comment by VPaulV** [comment]
I think it is a great idea, sadly owner of this repo is fairly unresponsive

**Comment by smhaller** [comment]
I would be happy to merge a pull request: i am also willing to give @yzx9 those rights.

**Comment by yzx9** [comment]
@smhaller , thank you for granting more rights. Your efforts are greatly appreciated. I understand that managing an OSP requires a lot of time and energy, especially on a volunteer basis. Quick responses can be challenging for both you and me ;)

**Comment by rercek** [comment]
FYI, I'm currently deploying a sharelatex/overleaf for my department and I integrated your solution for LDAP support. I use a bash script with git (merge) in order to apply modification from your files to future sharelatex version. You can have a look to this repository https://github.com/rercek/sharelatex-ldap/ I just created in order to share it with the community, more specificaly this [script here ](https://github.com/rercek/sharelatex-ldap/blob/main/ldap/updateldap.sh)

By the way, thank you very much for sharing your LDAP solution that seems to work really fine.
