### ISSUE TITLE
User settings broken

### ISSUE THREAD

**Issue by mooomooo** [smhaller/ldap-overleaf-sl#35]
When selecting "Account" -> "Account Settings", I get a "Something went wrong, sorry".

From the logs:

```
Cannot find module '../../../../modules/oauth2-server/app/src/OAuthPersonalAccessTokenManager'
Require stack:
- /overleaf/services/web/app/src/Features/User/UserPagesController.js
- /overleaf/services/web/app/src/router.js
- /overleaf/services/web/app/src/infrastructure/Server.js
- /overleaf/services/web/app.js

ENOENT: no such file or directory, open '/overleaf/services/web/app/views/user/settings/user-affiliations.pug'
    at /overleaf/services/web/app/views/user/settings.pug line 17
```

**Comment by smhaller** [comment]
Please re-open if the patch does not work for you

**Comment by mooomooo** [comment]
(I don't think I have permissions to re-open this issue?)

~~@smhaller Did you mean to remove all the files in `ldap-overleaf-sl/sharelatex/` ?  They're taken out via .gitignore in ca692f1, but they're still trying to be copied over in the Dockerfile~~

Woops I just saw the new instructions using the bash scripts. But `extract_files.sh` doesn't grab `navbar-marketing.pug.diff`.

Adding that back in makes the settings show up!  So it does seem like it's fixed, modulo two things to note:
- The "delete your account" link does nothing
- Trying to "request password reset" fails on oauth2 accounts, showing "Something went wrong. Please try again."

**Comment by mooomooo** [comment]
I broke these comments into their own new issues to let this one rest as completed.  Thanks!
