### ISSUE TITLE
Need some documentation

### ISSUE THREAD

**Issue by pikmin-rgb** [smhaller/ldap-overleaf-sl#37]
Hi !

I was wondering if it was possible to provide an example for a configuration with keycloak and traefik ?

Thank you !

**Comment by yzx9** [comment]
Hi there,

Thank you for your interest!

Regarding KeyCloak, it can be set up for OAuth login. I suggest trying to add an OIDC application and then configure the OAuth service. Please note that KeyCloak does not inherently provide LDAP functionality.

As for Traefik configuration, you might want to refer to our docker-compose.traefik.yml file.

If you need more details, please let me know, and I'll make time to provide them.

**Comment by yzx9** [comment]
Thank you for your issue. We hope the the provided information was helpful to you. This issue will now be closed due to prolonged inactivity. If you have more questions, feel free to reopen it or open a new one.
