### ISSUE TITLE
list instead of string when LDAP user have multiple mail address entries

### ISSUE THREAD

**Issue by Wurzelmann** [smhaller/ldap-overleaf-sl#62]
We encountered a problem with users with multiple mail address entries, the LDAP server's response became a list instead of a string and did not work.

The following little patch to **services/web/app/src/Features/Contacts/ContactController.js** fixed this:

the line

`entry['email'] = obj['mail']`

should be:

`entry['email'] = obj['uid'] + '@example.com'`

This filters the results and works for us.

**Comment by yzx9** [comment]
Thank you for your solution. I’ll close this issue as it’s a duplicate of #22. Further discussions can be continued there.
